// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCq2eFXTQsKFAZV99gwmYlm2kDgUShO5_Y',
    appId: '1:985161071274:web:63f6aff0ecda7c2bfeaed3',
    messagingSenderId: '985161071274',
    projectId: 'eyedoctorpro',
    authDomain: 'eyedoctorpro.firebaseapp.com',
    storageBucket: 'eyedoctorpro.appspot.com',
    measurementId: 'G-WKQE76RXZG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1kkkTGG8K4ISnsjdpN6ebrVTdB4fnWm8',
    appId: '1:985161071274:android:8688e083cb09df54feaed3',
    messagingSenderId: '985161071274',
    projectId: 'eyedoctorpro',
    storageBucket: 'eyedoctorpro.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRC2UHhnMAR2l1VZgclUHuojLzi-TEd9M',
    appId: '1:985161071274:ios:c068e94d8e1a4653feaed3',
    messagingSenderId: '985161071274',
    projectId: 'eyedoctorpro',
    storageBucket: 'eyedoctorpro.appspot.com',
    iosBundleId: 'com.example.eyedoctorPro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRC2UHhnMAR2l1VZgclUHuojLzi-TEd9M',
    appId: '1:985161071274:ios:c068e94d8e1a4653feaed3',
    messagingSenderId: '985161071274',
    projectId: 'eyedoctorpro',
    storageBucket: 'eyedoctorpro.appspot.com',
    iosBundleId: 'com.example.eyedoctorPro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCq2eFXTQsKFAZV99gwmYlm2kDgUShO5_Y',
    appId: '1:985161071274:web:f19e013f4a70a450feaed3',
    messagingSenderId: '985161071274',
    projectId: 'eyedoctorpro',
    authDomain: 'eyedoctorpro.firebaseapp.com',
    storageBucket: 'eyedoctorpro.appspot.com',
    measurementId: 'G-ZV9BNGSF59',
  );
}
