import 'package:carousel_slider/carousel_slider.dart';
import 'package:eyedoctor_pro/screens/image_detail.dart';
import 'package:eyedoctor_pro/widgets/navogation_bar.dart';
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:url_launcher/url_launcher.dart';

class MedicineScreen extends StatefulWidget {
  const MedicineScreen({super.key});

  @override
  State<MedicineScreen> createState() => _MedicineScreenState();
}

class _MedicineScreenState extends State<MedicineScreen>
    with SingleTickerProviderStateMixin {
  late AnimationController _controller;
  late Animation<double> _animation;

  final String disclaimerText =
      "Disclaimer: Use this app at your own risk. The results provided are generated by AI and may not always be accurate. Always consult a healthcare professional for proper guidance. This app is not a substitute for professional medical advice.";

  final List<Map<String, String>> panadolImages = [
    {
      'path': 'assets/images/images.jpeg',
      'description':
          '1. Reduce Screen Time\n2. Give Up Smoking\n3. Practise Eye Care Exercises\n4. Keep your Hands and Lens Clean\n5. Regular Eye Care Check-ups',
    },
    {
      'path': 'assets/images/maxresdefault.jpg',
      'description':
          '1. Maintain a Balanced Diet\n2. Protect Your Eyes from UV Light\nFollow the 20-20-20 Rule: For every 20 minutes of screen time, look at something 20 feet away for at least 20 seconds.',
    },
    {
      'path': 'assets/images/ec1.jpg',
      'description':
          '1.Wear sunglasses with UV protection to shield your eyes from harmful ultraviolet rays that can lead to cataracts and other vision problems. \n2.Take regular breaks from screen time by following the 20-20-20 rule: every 20 minutes, look at something 20 feet away for 20 seconds. \n3.Maintain a healthy diet rich in antioxidants, omega-3 fatty acids, and vitamins A, C, and E, which are beneficial for eye health. \nGet regular eye exams to detect early signs of eye conditions like glaucoma, macular degeneration, and diabetic retinopathy. \n4.Practice proper hygiene when handling contact lenses by washing your hands thoroughly before inserting or removing them. \n',
    },
    {
      'path': 'assets/images/ec2.jpg',
      'description':
          '1.Ensure proper lighting when reading or working to reduce eye strain. Use bright, indirect light and avoid glare on screens. \n2.Blink frequently to keep your eyes moist and prevent dryness, especially during long hours of screen use. \n3.Stay hydrated by drinking enough water throughout the day to maintain proper tear production and eye moisture. \n4.Limit screen time by adjusting your routine and engaging in outdoor activities to give your eyes a break from digital devices. \n5.Quit smoking to reduce the risk of cataracts, age-related macular degeneration, and other eye diseases linked to tobacco use. \n',
    },
    {
      'path': 'assets/images/ec3.jpeg',
      'description':
          '1. Avoid touching or rubbing your eyes to reduce the risk of spreading conjunctivitis (pink eye) or eye flu. \n2. Wash your hands frequently with soap and water to prevent the transmission of bacteria and viruses that cause eye infections. \n3. Use a clean tissue or cotton pad to wipe away any discharge from your eyes and dispose of it properly. \n4. Avoid sharing personal items like towels, pillows, or makeup to prevent spreading the infection. \n5. Stay home from work or school to prevent the spread of eye infections, especially during the contagious stages of pink eye or eye flu. \n6. Use over-the-counter eye drops to soothe irritation and reduce redness, but consult a doctor if symptoms persist or worsen. \n'
    },
  ];

  final List<Map<String, String>> doctors = [
    {
      'name': 'Dr. Anwar Ahmed Gul',
      'location': 'Islamabad',
      'description':
          'Eye Specialist and Eye Surgeon with 17 years of experience, practicing at Ali Medical Centre.',
      'contact': '0512306708',
      'emoji': '👓'
    },
    {
      'name': 'Dr. Atif Bashir Chohan',
      'location': 'Islamabad',
      'description':
          'Eye Specialist and Eye Surgeon with 25 years of experience, practicing at Chohan Eye Clinic. ',
      'contact': '0512255773',
      'emoji': '👓'
    },
    {
      'name': 'Dr. Inayatullah Khan',
      'location': 'Islamabad',
      'description':
          'Eye Specialist and Eye Surgeon with 16 years of experience, practicing at Ali Medical Centre.',
      'contact': '0515772288',
      'emoji': '👓'
    },
  ];

  @override
  void initState() {
    super.initState();

    _controller = AnimationController(
      vsync: this,
      duration: const Duration(seconds: 15),
    )..repeat(reverse: false);

    _animation = Tween<double>(begin: 1.0, end: -1.0).animate(_controller);
  }

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  void _launchDialer(String phoneNumber) async {
    final Uri launchUri = Uri(
      scheme: 'tel',
      path: phoneNumber,
    );

    try {
      if (await canLaunchUrl(launchUri)) {
        await launchUrl(launchUri);
      } else {
        print('Could not launch $launchUri');
      }
    } catch (e) {
      print('Error launching dialer: $e');
    }
  }

  void _showDoctorList() {
    showModalBottomSheet(
      context: context,
      isScrollControlled: true,
      builder: (BuildContext context) {
        return Container(
          height: 400,
          padding: const EdgeInsets.all(16.0),
          decoration: BoxDecoration(
            color: const Color(0xff72b8d6),
            borderRadius: BorderRadius.vertical(top: Radius.circular(20)),
          ),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Text(
                'Available Doctors',
                style: GoogleFonts.nunitoSans(
                  fontSize: 24,
                  fontWeight: FontWeight.bold,
                ),
              ),
              const SizedBox(height: 16),
              Expanded(
                child: ListView.builder(
                  itemCount: doctors.length,
                  itemBuilder: (context, index) {
                    return Card(
                      margin: const EdgeInsets.symmetric(vertical: 8),
                      child: ListTile(
                        leading: Text(
                          doctors[index]['emoji']!,
                          style: const TextStyle(fontSize: 30),
                        ),
                        title: Text(
                          doctors[index]['name']!,
                          style: GoogleFonts.nunitoSans(
                              fontWeight: FontWeight.bold),
                        ),
                        subtitle: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Text(doctors[index]['location']!),
                            Text(doctors[index]['description']!),
                            Text('Contact: ${doctors[index]['contact']!}'),
                          ],
                        ),
                        onTap: () {
                          _launchDialer(doctors[index]['contact']!);
                        },
                      ),
                    );
                  },
                ),
              ),
              Center(
                child: ElevatedButton(
                  onPressed: () {
                    Navigator.pop(context);
                  },
                  child: const Text('Close'),
                ),
              ),
            ],
          ),
        );
      },
    );
  }

  @override
  Widget build(BuildContext context) {
    return SafeArea(
      child: Scaffold(
        body: Container(
          decoration: const BoxDecoration(
            gradient: LinearGradient(colors: [
              Color(0xfface3f4),
              Color(0xff7cc0db),
              Color(0xff57a5c8),
            ], begin: Alignment.topLeft, end: Alignment.bottomRight),
          ),
          child: Column(
            children: [
              // Scrolling Disclaimer
              Container(
                height: 30,
                color: Colors.yellow,
                child: AnimatedBuilder(
                  animation: _animation,
                  builder: (context, child) {
                    return FractionalTranslation(
                      translation: Offset(_animation.value, 0.0),
                      child: child,
                    );
                  },
                  child: Text(
                    disclaimerText,
                    style: const TextStyle(
                      color: Colors.black,
                      fontSize: 14,
                      fontWeight: FontWeight.bold,
                    ),
                    softWrap: false,
                    overflow: TextOverflow.visible,
                  ),
                ),
              ),
              const SizedBox(height: 50),
              Center(
                child: Text(
                  "Tips",
                  style: GoogleFonts.nunitoSans(
                    fontSize: 26,
                    fontWeight: FontWeight.bold,
                  ),
                ),
              ),
              const SizedBox(height: 20),
              Container(
                height: 267,
                width: 367,
                decoration: BoxDecoration(
                  color: Colors.white,
                  borderRadius: BorderRadius.circular(15),
                ),
                child: CarouselSlider(
                  options: CarouselOptions(
                    autoPlay: true,
                    viewportFraction: 1.01,
                    enlargeCenterPage: true,
                    aspectRatio: 16 / 9,
                    autoPlayInterval: const Duration(seconds: 3),
                  ),
                  items: panadolImages.map((imageData) {
                    return Builder(
                      builder: (BuildContext context) {
                        return GestureDetector(
                          onTap: () {
                            Navigator.push(
                              context,
                              MaterialPageRoute(
                                builder: (context) => ImageDetailScreen(
                                  imagePath: imageData['path']!,
                                  description: imageData['description']!,
                                ),
                              ),
                            );
                          },
                          child: Container(
                            width: double.infinity,
                            margin: const EdgeInsets.symmetric(horizontal: 5.0),
                            decoration: BoxDecoration(
                              borderRadius: BorderRadius.circular(10),
                              image: DecorationImage(
                                image: AssetImage(imageData['path']!),
                                fit: BoxFit.cover,
                              ),
                            ),
                          ),
                        );
                      },
                    );
                  }).toList(),
                ),
              ),
              const SizedBox(height: 20),
              Padding(
                padding: const EdgeInsets.only(left: 145),
                child: Card(
                  elevation: 8.0,
                  shape: RoundedRectangleBorder(
                    borderRadius: BorderRadius.circular(25.0),
                  ),
                  child: GestureDetector(
                    onTap: _showDoctorList,
                    child: Container(
                      height: 49,
                      width: 170,
                      decoration: BoxDecoration(
                        color: const Color(0xff4c9dc2),
                        borderRadius: BorderRadius.circular(30),
                        border: Border.all(color: Colors.white),
                      ),
                      child: Center(
                        child: Text(
                          'Consult',
                          style: GoogleFonts.nunitoSans(
                            fontSize: 26,
                            color: Colors.white,
                            fontWeight: FontWeight.bold,
                          ),
                        ),
                      ),
                    ),
                  ),
                ),
              ),
              const SizedBox(height: 220),
              CustomNavigator(),
            ],
          ),
        ),
      ),
    );
  }
}
